#pragma once

#define APP_VERSION_MAJOR 0
#define APP_VERSION_MINOR 0
#define APP_VERSION_PATCH 1
#define APP_BUILD_NUMBER 65
#define APP_GIT_HASH "c0a3b86"
#define APP_VERSION_STRING "v0.0.1 (Build 65 • c0a3b86)"
#define APP_SHORT_VERSION_STRING "0.0.1+b65"
